### ISSUE TITLE
White Direwolfs are too strong

### ISSUE THREAD

**Issue by sogartar** [Battle-Brothers-Legends/Legends-Bugs#161]
**Describe what you think the current issue is**
White Direwolves are either too strong or are too many in a pack. They appear 5 or more in a pack.
For reference look at this massacre https://www.youtube.com/watch?v=eRaHigQ4n6A&ab_channel=Lorthorn

**Suggest how you'd fix this issue**
Maybe it should be 1 in a pack with some Direwolves. Even 1 seems too strong.

**Comment by Alykar** [comment]
Yeah, Will add to it.
First of all there is probably should be only one in the pack. I have a "Lone Wolf" party, with main guy with long sword. lvl 15, 100 mil attack, 41 def, 216/325 armor, + Lone Wolf skill. 2 of that nightmarish things in the snow always kill him.
Its shouldn't go as surprise, that something can kill my party on hardest start, but anyway i cannot even run from them. its just madness.

They have what 6 tile for movement? 12AP or something like that? 4 attacks, nimble, footwork, owerwhelm, fast adaptation, and what else? Plus armor, shit tone of armor, and a lot of HP.
In the end of first round i down by -40% of meele skill, half of my armor, because they also have a shit tone of damage, and it will grow. 3 round and im always dead. I cannot run from them, even if i drop all my gear, i cannot do anything.

Why on earth a white colored big dog is more of an apponent then fucking trolls, lanwirms, undead, or any other beasts?

I suggest remove atleast half of their talants, its a wolf after all, not a ninja-acrobat ffs,
